// Generated by CoffeeScript 1.6.2
(function() {
  var TextRepo, fs;

  fs = require('fs');

  TextRepo = (function() {
    TextRepo.NOT_FOUND = 'not found';

    TextRepo.prototype.records = null;

    TextRepo.prototype.path = '';

    TextRepo.prototype.hash = {};

    function TextRepo(path) {
      this.path = path;
    }

    TextRepo.prototype.setupHash = function(records) {
      var item, key, _i, _len, _results;

      _results = [];
      for (_i = 0, _len = records.length; _i < _len; _i++) {
        item = records[_i];
        key = item.split(' ')[0].toLowerCase();
        _results.push(this.hash[key] = item);
      }
      return _results;
    };

    TextRepo.prototype.queryByKey = function(value) {
      var hashKey;

      value = value.toLowerCase();
      if (!this.records) {
        this.records = fs.readFileSync(this.path).toString().split("\n");
        this.setupHash(this.records);
      }
      for (hashKey in this.hash) {
        if (hashKey.indexOf(value) > -1) {
          return this.hash[hashKey];
        }
      }
      return TextRepo.NOT_FOUND;
    };

    module.exports = TextRepo;

    return TextRepo;

  })();

}).call(this);

/*
//@ sourceMappingURL=textRepo.map
*/
